[req]
default_bits = 4096
default_keyfile = deutsche_bank_private_key.pem
default_md = sha256
distinguished_name = req_distinguished_name
req_extensions = v3_req
prompt = no

[req_distinguished_name]
C = DE
ST = HESSE
L = FRANKFURT
O = DEUTSCHE BANK AG
OU = IT SECURITY
CN = 193.150.166.1
emailAddress = security@deutsche-bank.com

[v3_req]
basicConstraints = CA:FALSE
keyUsage = nonRepudiation, digitalSignature, keyEncipherment
extendedKeyUsage = serverAuth, clientAuth
subjectAltName = @alt_names

[alt_names]
DNS.1 = deutsche-bank.com
DNS.2 = db.com
DNS.3 = ebanking.db.com
IP.1 = 193.150.166.1
